-- Pre-Supabase audit pass. Three groups of changes:
--
--   1. Type narrowing: bounded strings (ISO codes, room codes, session
--      IDs, enum kinds, user-entered names with Zod max() caps) move
--      from `text` to `varchar(N)`. No data is lost — every cap here
--      is verified against the corresponding Zod validator or against
--      the generator that emits the column.
--   2. CHECK constraints: cheap correctness fences for enums + counters
--      whose invalid states the app never produces but nothing
--      structurally prevents (a stray UPDATE could land us in an
--      illegal state today). Adding these now means Supabase inherits
--      a stricter schema and any future regression trips at write time.
--   3. Drop one redundant single-column index: `trivia_answers_room_idx`
--      duplicates the leftmost prefix of the table's primary key
--      `(room_id, session_id, country_code)`, which the planner is
--      happy to use for room-only lookups.
--
-- Each statement runs standalone via the @neondatabase/serverless
-- HTTP driver (the migration runner can't wrap the file in a
-- transaction). Order matters: drop the dependent view first, then
-- type narrowings, then CHECK adds, then the index drop, then
-- recreate the view against the new column types. Any single
-- failure aborts the run and the rest is safe to re-apply.

-- ─── 0. Drop dependent view ─────────────────────────────────────

-- The `scoreboard` view from migration 0000 references
-- votes.country_code, so Postgres blocks any type change on that
-- column. Drop it now; we recreate at the end against the
-- narrowed type with the exact same shape.
DROP VIEW IF EXISTS "scoreboard";

-- ─── 1. Type narrowing ──────────────────────────────────────────

-- Room codes: 6-char uppercase alphanumeric, generated by
-- customAlphabet("23456789ABCDEFGHJKMNPQRSTUVWXYZ", 6). varchar(8)
-- gives headroom if we ever lengthen.
ALTER TABLE "rooms" ALTER COLUMN "code" TYPE varchar(8);

-- Room name: user-entered, capped at 60 by Zod (see app/api/rooms
-- /route.ts and app/api/admin/rooms/[code]/route.ts).
ALTER TABLE "rooms" ALTER COLUMN "name" TYPE varchar(60);

-- Show-status enum: not_started | in_progress | break | ended.
ALTER TABLE "rooms" ALTER COLUMN "show_status" TYPE varchar(16);

-- ISO 3166-1 alpha-2 (lowercase). Always exactly two chars.
ALTER TABLE "rooms" ALTER COLUMN "home_country_code" TYPE varchar(2);
ALTER TABLE "rooms" ALTER COLUMN "now_playing_code" TYPE varchar(2);
ALTER TABLE "votes" ALTER COLUMN "country_code" TYPE varchar(2);
ALTER TABLE "reactions" ALTER COLUMN "country_code" TYPE varchar(2);
ALTER TABLE "official_results" ALTER COLUMN "country_code" TYPE varchar(2);
ALTER TABLE "room_results" ALTER COLUMN "country_code" TYPE varchar(2);
ALTER TABLE "trivia_answers" ALTER COLUMN "country_code" TYPE varchar(2);

-- Bonus-bet picks: ISO2 country code OR the sentinel "NONE" (4 chars).
ALTER TABLE "voters" ALTER COLUMN "bet_wooden_spoon" TYPE varchar(4);
ALTER TABLE "voters" ALTER COLUMN "bet_lt_12_to" TYPE varchar(4);
ALTER TABLE "voters" ALTER COLUMN "bet_highest_big5" TYPE varchar(4);
ALTER TABLE "voters" ALTER COLUMN "bet_jury_winner" TYPE varchar(4);
ALTER TABLE "voters" ALTER COLUMN "bet_televote_winner" TYPE varchar(4);

-- Session IDs: minted by ensureSessionId() as `s_` + 12 base36 chars
-- (lib/use-identity.ts), so always 14 chars. varchar(64) is generous
-- in case we ever swap the generator.
ALTER TABLE "voters" ALTER COLUMN "session_id" TYPE varchar(64);
ALTER TABLE "chat_messages" ALTER COLUMN "session_id" TYPE varchar(64);
ALTER TABLE "chat_reactions" ALTER COLUMN "session_id" TYPE varchar(64);
ALTER TABLE "trivia_answers" ALTER COLUMN "session_id" TYPE varchar(64);
ALTER TABLE "push_subscriptions" ALTER COLUMN "session_id" TYPE varchar(64);

-- User-entered display names: capped at 40 by Zod across every write
-- path that accepts them (chat, reactions, votes, push).
ALTER TABLE "voters" ALTER COLUMN "name" TYPE varchar(40);
ALTER TABLE "chat_messages" ALTER COLUMN "name" TYPE varchar(40);
ALTER TABLE "chat_reactions" ALTER COLUMN "name" TYPE varchar(40);
ALTER TABLE "push_subscriptions" ALTER COLUMN "voter_name" TYPE varchar(40);

-- Avatar IDs: slug-form like "kaarija-2023" from lib/avatars.ts.
-- Longest entries sit around 20 chars; varchar(40) covers any future
-- naming.
ALTER TABLE "chat_messages" ALTER COLUMN "avatar_id" TYPE varchar(40);

-- Chat message kind enum (8 values today).
ALTER TABLE "chat_messages" ALTER COLUMN "kind" TYPE varchar(16);

-- Chat helper cache kind enum (translate | beginner) + lang code.
ALTER TABLE "chat_helper_cache" ALTER COLUMN "kind" TYPE varchar(16);
ALTER TABLE "chat_helper_cache" ALTER COLUMN "lang" TYPE varchar(2);


-- ─── 2. CHECK constraints ──────────────────────────────────────

-- Eurovision points scale. POINT_VALUES in lib/db/schema.ts is the
-- canonical source of truth.
ALTER TABLE "votes"
  ADD CONSTRAINT "votes_points_chk"
  CHECK ("points" IN (1, 2, 3, 4, 5, 6, 7, 8, 10, 12));

-- Reaction counter only ever increments; this guards an accidental
-- negative write.
ALTER TABLE "reactions"
  ADD CONSTRAINT "reactions_count_nonneg_chk"
  CHECK ("count" >= 0);

-- Eurovision placements are 1..N (no zero or negative).
ALTER TABLE "official_results"
  ADD CONSTRAINT "official_results_placement_chk"
  CHECK ("placement" >= 1);
ALTER TABLE "room_results"
  ADD CONSTRAINT "room_results_placement_chk"
  CHECK ("placement" >= 1);

-- "Where will home country finish?" prediction shares the same 1..N
-- range as the official placement. Nullable, so NULL is fine.
ALTER TABLE "voters"
  ADD CONSTRAINT "voters_home_country_prediction_chk"
  CHECK ("home_country_prediction" IS NULL OR "home_country_prediction" >= 1);

-- LT-total-points bet: 0 or positive. Nullable.
ALTER TABLE "voters"
  ADD CONSTRAINT "voters_bet_lt_total_points_chk"
  CHECK ("bet_lt_total_points" IS NULL OR "bet_lt_total_points" >= 0);

-- Show-status enum lock. Mirrors the Zod enum in
-- app/api/admin/live/route.ts.
ALTER TABLE "rooms"
  ADD CONSTRAINT "rooms_show_status_chk"
  CHECK ("show_status" IN ('not_started', 'in_progress', 'break', 'ended'));

-- Running-order position: 1..N. Nullable.
ALTER TABLE "rooms"
  ADD CONSTRAINT "rooms_running_order_pos_chk"
  CHECK ("running_order_pos" IS NULL OR "running_order_pos" >= 1);

-- Trivia-cap: at least one answerer per question if a cap is set.
ALTER TABLE "rooms"
  ADD CONSTRAINT "rooms_trivia_max_answerers_chk"
  CHECK ("trivia_max_answerers" IS NULL OR "trivia_max_answerers" >= 1);

-- Chat-message kind enum (ChatMessageKind in lib/db/schema.ts).
ALTER TABLE "chat_messages"
  ADD CONSTRAINT "chat_messages_kind_chk"
  CHECK ("kind" IN (
    'text', 'gif', 'image', 'bingo_strike',
    'system', 'now_playing', 'results', 'trivia'
  ));

-- Chat-helper cache: kind is one of the two AI-rewrite features we
-- back through this table.
ALTER TABLE "chat_helper_cache"
  ADD CONSTRAINT "chat_helper_cache_kind_chk"
  CHECK ("kind" IN ('translate', 'beginner'));
ALTER TABLE "chat_helper_cache"
  ADD CONSTRAINT "chat_helper_cache_hits_chk"
  CHECK ("hits" >= 0);

-- Trivia bank always emits exactly 4 choices (lib/trivia.ts), so
-- valid indices are 0..3.
ALTER TABLE "trivia_answers"
  ADD CONSTRAINT "trivia_answers_choice_chk"
  CHECK ("choice_index" >= 0 AND "choice_index" <= 3);

-- Rate-limit hit counter is monotonically non-negative.
ALTER TABLE "rate_limits"
  ADD CONSTRAINT "rate_limits_hits_chk"
  CHECK ("hits" >= 0);


-- ─── 3. Drop redundant index ───────────────────────────────────

-- Primary key on trivia_answers is (room_id, session_id, country_code).
-- Postgres uses the leftmost prefix of the PK btree for `WHERE room_id
-- = $1` lookups, so the single-column index on room_id was redundant.
DROP INDEX IF EXISTS "trivia_answers_room_idx";


-- ─── 4. Recreate scoreboard view ───────────────────────────────

-- Same definition as the one originally created in 0000, but now
-- typed against the narrowed votes.country_code (varchar(2)). The
-- view body itself is unchanged.
CREATE OR REPLACE VIEW "scoreboard" AS
SELECT
  v.room_id                                AS room_id,
  votes.country_code                       AS country_code,
  COALESCE(SUM(votes.points), 0)           AS total_points,
  SUM(CASE WHEN votes.points = 12 THEN 1 ELSE 0 END) AS points_12,
  SUM(CASE WHEN votes.points = 10 THEN 1 ELSE 0 END) AS points_10,
  SUM(CASE WHEN votes.points =  8 THEN 1 ELSE 0 END) AS points_8,
  SUM(CASE WHEN votes.points =  7 THEN 1 ELSE 0 END) AS points_7,
  SUM(CASE WHEN votes.points =  6 THEN 1 ELSE 0 END) AS points_6,
  SUM(CASE WHEN votes.points =  5 THEN 1 ELSE 0 END) AS points_5,
  SUM(CASE WHEN votes.points =  4 THEN 1 ELSE 0 END) AS points_4,
  SUM(CASE WHEN votes.points =  3 THEN 1 ELSE 0 END) AS points_3,
  SUM(CASE WHEN votes.points =  2 THEN 1 ELSE 0 END) AS points_2,
  SUM(CASE WHEN votes.points =  1 THEN 1 ELSE 0 END) AS points_1
FROM votes
JOIN voters v ON v.id = votes.voter_id
GROUP BY v.room_id, votes.country_code;
