"use client";

import { useMemo } from "react";
import { motion, AnimatePresence } from "motion/react";
import { useOthers, useSelf } from "@/lib/liveblocks";
import { Flag } from "@/components/flag";
import { getAvatar } from "@/lib/avatars";

// Apple-Watch-style honeycomb of online users, anchored to the lower-left
// corner so it stays out of the way of the reactions bar (lower-center)
// and the live vote CTA (page bottom). Hex layout with concentric rings:
//
//             ring 1
//          ring 0 (centre)
//             ring 1
//
// We only show up to MAX_TILES at once; overflow renders as a "+N" pill
// in the spare slot. Hexes are drawn with clip-path so they stay crisp
// at any size.

const TILE = 36; // px diameter of each tile
const GAP = 4;   // px between tiles

// Hex axial offsets for tiles 1..18 (centre is index 0). Coordinates use
// the standard "pointy-top" hex math: column step = TILE * 0.866 +
// gap * 0.866; row step = TILE * 0.75 + gap. We offset every other row
// so they nest. Generated by hand for a near-circular packing.
const HEX_OFFSETS: Array<[number, number]> = [
  [0, 0],
  // Ring 1 (6 around centre)
  [1, 0], [-1, 0], [0.5, 1], [-0.5, 1], [0.5, -1], [-0.5, -1],
  // Ring 2 (12 more)
  [2, 0], [-2, 0],
  [1.5, 1], [-1.5, 1], [1.5, -1], [-1.5, -1],
  [1, 2], [-1, 2], [1, -2], [-1, -2],
  [0, 2], [0, -2],
];

const MAX_TILES = HEX_OFFSETS.length;

export function HoneycombPresence() {
  const others = useOthers();
  const self = useSelf();

  // Self always renders first (centre), then others in connection order.
  // Filter `null` self defensively (Liveblocks can briefly hand back null
  // during the initial connection handshake).
  const all = useMemo(() => {
    const list = [self, ...others].filter(Boolean) as NonNullable<typeof self>[];
    // Stable order so a single tile doesn't re-pack on every render.
    return list.slice(0, MAX_TILES);
  }, [self, others]);

  if (all.length <= 1) {
    // Nobody else is online; skip the honeycomb to avoid a lonely
    // single-tile bubble. Self-only state is already implied by the
    // existing UI.
    return null;
  }

  const overflow = others.length + 1 - MAX_TILES;

  return (
    <div className="pointer-events-none fixed bottom-4 left-4 z-20">
      <div
        className="relative"
        style={{
          width: TILE * 5,
          height: TILE * 5,
        }}
      >
        <AnimatePresence>
          {all.map((u, i) => {
            const [cx, cy] = HEX_OFFSETS[i] ?? [0, 0];
            // The hex grid uses 0.866 (cos 30°) for the horizontal step
            // and 0.75 for the vertical step so rows interlock cleanly.
            const x = (TILE + GAP) * cx * 0.866;
            const y = (TILE + GAP) * cy * 0.75;
            const info = u.info;
            const liveName = u.presence?.name ?? info?.name ?? "Guest";
            const initial =
              liveName.trim().charAt(0).toUpperCase() || "?";
            const avatarId = u.presence?.avatar ?? null;
            const avatar = getAvatar(avatarId);
            return (
              <motion.div
                key={u.connectionId}
                initial={{ opacity: 0, scale: 0.4 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.4 }}
                transition={{
                  type: "spring",
                  stiffness: 360,
                  damping: 24,
                  delay: i * 0.04,
                }}
                title={
                  avatar
                    ? `${liveName} · ${avatar.artist} (${avatar.country.toUpperCase()} ${avatar.year})`
                    : liveName
                }
                className="absolute pointer-events-auto"
                style={{
                  left: "50%",
                  top: "50%",
                  width: TILE,
                  height: TILE,
                  transform: `translate(${x - TILE / 2}px, ${y - TILE / 2}px)`,
                }}
              >
                <div
                  className="h-full w-full overflow-hidden ring-1 ring-white/20 shadow-md"
                  style={{
                    clipPath:
                      "polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)",
                  }}
                >
                  {avatar ? (
                    <Flag
                      code={avatar.country}
                      size="md"
                      className="h-full w-full rounded-none"
                    />
                  ) : (
                    <div
                      className="h-full w-full grid place-items-center font-semibold text-white text-sm"
                      style={{ background: info?.color ?? "#7ce0d8" }}
                    >
                      {initial}
                    </div>
                  )}
                </div>
              </motion.div>
            );
          })}

          {overflow > 0 && (
            <motion.div
              key="overflow"
              initial={{ opacity: 0, scale: 0.4 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.4 }}
              className="absolute"
              style={{
                left: "50%",
                top: "50%",
                width: TILE,
                height: TILE,
                transform: `translate(${
                  (TILE + GAP) * 2 * 0.866 - TILE / 2
                }px, ${(TILE + GAP) * 2 * 0.75 - TILE / 2}px)`,
              }}
            >
              <div
                className="h-full w-full grid place-items-center bg-flamingo/40 ring-1 ring-flamingo/60 text-xs font-display tabular-nums text-white"
                style={{
                  clipPath:
                    "polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)",
                }}
              >
                +{overflow}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
