export const countries = [
  {
    code: "no",
    name: "Norway",
    flag: "🇳🇴",
    artist: "Kyle Alessandro",
    song: "Lighter",
    order: 1,
  },
  {
    code: "lu",
    name: "Luxembourg",
    flag: "🇱🇺",
    artist: "Laura Thorn",
    song: "La Poupée Monte Le Son",
    order: 2,
  },
  {
    code: "ee",
    name: "Estonia",
    flag: "🇪🇪",
    artist: "Tommy Cash",
    song: "Espresso Macchiato",
    order: 3,
  },
  {
    code: "il",
    name: "Israel",
    flag: "🇮🇱",
    artist: "Yuval Raphael",
    song: "New Day Will Rise",
    order: 4,
  },
  {
    code: "lt",
    name: "Lithuania",
    flag: "🇱🇹",
    artist: "Katarsis",
    song: "Tavo Akys",
    order: 5,
  },
  {
    code: "es",
    name: "Spain",
    flag: "🇪🇸",
    artist: "Melody",
    song: "ESA DIVA",
    order: 6,
  },
  {
    code: "ua",
    name: "Ukraine",
    flag: "🇺🇦",
    artist: "Ziferblat",
    song: "Bird of Pray",
    order: 7,
  },
  {
    code: "gb",
    name: "United Kingdom",
    flag: "🇬🇧",
    artist: "Remember Monday",
    song: "What The Hell Just Happened?",
    order: 8,
  },
  {
    code: "at",
    name: "Austria",
    flag: "🇦🇹",
    artist: "JJ",
    song: "Wasted Love",
    order: 9,
  },
  {
    code: "is",
    name: "Iceland",
    flag: "🇮🇸",
    artist: "VÆB",
    song: "RÓA",
    order: 10,
  },
  {
    code: "lv",
    name: "Latvia",
    flag: "🇱🇻",
    artist: "Tautumeitas",
    song: "Bur Man Laimi",
    order: 11,
  },
  {
    code: "nl",
    name: "Netherlands",
    flag: "🇳🇱",
    artist: "Claude",
    song: "C'est La Vie",
    order: 12,
  },
  {
    code: "fi",
    name: "Finland",
    flag: "🇫🇮",
    artist: "Erika Vikman",
    song: "ICH KOMME",
    order: 13,
  },
  {
    code: "it",
    name: "Italy",
    flag: "🇮🇹",
    artist: "Lucio Corsi",
    song: "Volevo Essere Un Duro",
    order: 14,
  },
  {
    code: "pl",
    name: "Poland",
    flag: "🇵🇱",
    artist: "Justyna Steczkowska",
    song: "GAJA",
    order: 15,
  },
  {
    code: "de",
    name: "Germany",
    flag: "🇩🇪",
    artist: "Abor & Tynna",
    song: "Baller",
    order: 16,
  },
  {
    code: "gr",
    name: "Greece",
    flag: "🇬🇷",
    artist: "Klavdia",
    song: "Asteromáta",
    order: 17,
  },
  {
    code: "am",
    name: "Armenia",
    flag: "🇦🇲",
    artist: "PARG",
    song: "SURVIVOR",
    order: 18,
  },
  {
    code: "ch",
    name: "Switzerland",
    flag: "🇨🇭",
    artist: "Zoë Më",
    song: "Voyage",
    order: 19,
  },
  {
    code: "mt",
    name: "Malta",
    flag: "🇲🇹",
    artist: "Miriana Conte",
    song: "SERVING",
    order: 20,
  },
  {
    code: "pt",
    name: "Portugal",
    flag: "🇵🇹",
    artist: "NAPA",
    song: "Deslocado",
    order: 21,
  },
  {
    code: "dk",
    name: "Denmark",
    flag: "🇩🇰",
    artist: "Sissal",
    song: "Hallucination",
    order: 22,
  },
  {
    code: "se",
    name: "Sweden",
    flag: "🇸🇪",
    artist: "KAJ",
    song: "Bara Bada Bastu",
    order: 23,
  },
  {
    code: "fr",
    name: "France",
    flag: "🇫🇷",
    artist: "Louane",
    song: "maman",
    order: 24,
  },
  {
    code: "sm",
    name: "San Marino",
    flag: "🇸🇲",
    artist: "Gabry Ponte",
    song: "Tutta L'Italia",
    order: 25,
  },
  {
    code: "al",
    name: "Albania",
    flag: "🇦🇱",
    artist: "Shkodra Elektronike",
    song: "ZjermPlease",
    order: 26,
  },
]
